servers:
  - name: server1
    ip: 192.168.1.101
    public_ip: 1.2.3.4
  - name: server2
    ip: 192.168.1.102
  - name: test1
    ip: 192.168.1.6
    public_ip: 5.6.7.8
  - name: test2
    ip: 192.168.1.66
